### PR TITLE
Update to turbodbc 2.5.0. Also bump pyarrow requirements to 0.8.*

### PR DESCRIPTION
**Pull request by MathMagique**

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by dhirschfeld** [comment]
The appveyor build fails with:
```
Can't build C:\projects\turbodbc-feedstock\recipe due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - numpy 1.11.*
  - pyarrow 0.8.*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```
...so it looks like the numpy dep needs to be updated?

**Comment by dhirschfeld** [comment]
Mystery solved!
```
λ conda info pyarrow=0.8*

pyarrow 0.8.0 py35_vc14_0
-------------------------
dependencies:
    arrow-cpp 0.8.0
    numpy >=1.10
    pandas
    parquet-cpp 1.4.*
    python 3.5*
    setuptools
    six

pyarrow 0.8.0 py36_vc14_0
-------------------------
dependencies:
    arrow-cpp 0.8.0
    numpy >=1.12    # <-------- !!!
    pandas
    parquet-cpp 1.4.*
    python 3.6*
    setuptools
    six
```

**Comment by dhirschfeld** [comment]
Since numpy 1.14 is out already I'd be inclined just to bump the numpy dep to 1.12 across the board.

If you wanted to be more permissive you could use a `[win and py>=36]` as they do in `pyarrow`

**Comment by MathMagique** [comment]
Closing this in favor of #14

**Pull request closed without merging**
