### PR TITLE
Update to turbodbc 2.0.0

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
cc @MathMagique @xhochy

**Comment by MathMagique** [comment]
@wesm Thanks for updating!

**Comment by wesm** [comment]
I have not. Is there an import or some way to test in the conda build that it's linking properly?

**Comment by MathMagique** [comment]
If `import turbodbc_arrow_support` works, the feature itself should work.

**Comment by wesm** [comment]
Added the import check

**Comment by wesm** [comment]
Merge away!

**Comment by xhochy** [comment]
Amazing that this worked out of the box.

**Pull request merged**
