### PR TITLE
Rebuild for arrow v10

### PR DESCRIPTION
**Pull request by h-vetinari**
Based on #84 

Closes #84

### CODE REVIEW

**Comment by h-vetinari** [comment]
It seems windows has problems with finding `arrow_python.dll` from site-packages. The following warning is not really crucial, but indicative of which DLL is most likely at fault here.
```
   INFO (turbodbc,Lib/site-packages/turbodbc_arrow_support.cp39-win_amd64.pyd): Needed DSO Library/bin/arrow.dll found in conda-forge::libarrow-10.0.1-h226723c_3_cpu
WARNING (turbodbc,Lib/site-packages/turbodbc_arrow_support.cp39-win_amd64.pyd): $RPATH/arrow_python.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

During the test phase, things then fail with:
```
import: 'turbodbc_arrow_support'
Traceback (most recent call last):
  File "D:\bld\turbodbc_1671499558762\test_tmp\run_test.py", line 5, in <module>
    import turbodbc_arrow_support
ImportError: DLL load failed while importing turbodbc_arrow_support: The specified module could not be found.
```

The libraries look [specified](https://github.com/blue-yonder/turbodbc/blob/4.5.6/setup.py#L202-L214) correctly in `setup.py`, and I double-checked that the outputs of `pyarrow.get_libraries()` resp. `pyarrow.get_library_dirs()` on windows. 

So I'm not sure where this might be going off the rails...

**Comment by david-engelmann** [comment]
[I believe this is the info you are looking for](https://github.com/apache/arrow/commit/d31f3d9439d94803f1dc5900e4df8607226fa925)

**Comment by david-engelmann** [comment]
Should these adjustments be made in the turbodbc repo? [I've created a feature branch, if so I'll create a PR to turbodbc](https://github.com/david-engelmann/turbodbc/tree/de-setup-cleanup)!

**Comment by h-vetinari** [comment]
> @h-vetinari [I believe this is the info you are looking for](https://github.com/apache/arrow/commit/d31f3d9439d94803f1dc5900e4df8607226fa925)

I'm not sure TBH, and `CONDA_DLL_SEARCH_MODIFICATION` is a big hammer that we shouldn't have to use (see the commit message in the [patch](https://github.com/conda-forge/python-feedstock/blob/3.10/recipe/patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch) that adds it for details). It's also not needed for building pyarrow in conda-forge.

So assuming that's the issue, I think it would be somewhat better to try `os.add_dll_directory()`, but what I don't understand is how the DLL is found during the build, and its location is then forgotten. There are several other packages that have some DLLs in site-packages, and it's the first time I see this fail, so I'm wondering if there isn't also something else at play.

@xhochy @hmaarrfk @jaimergp 
If you have any ideas/experiences here, your insights would be much appreciated.

> Should these adjustments be made in the turbodbc repo? [I've created a feature branch, if so I'll create a PR to turbodbc](https://github.com/david-engelmann/turbodbc/tree/de-setup-cleanup)!

Windows definitely needs the C++17 flag (the arrow headers use C++17 features), but `-D_LIBCPP_DISABLE_AVAILABILITY` is very conda-forge specific. I mean, if you're willing to carry that upstream it would make our lives easier (no patching), but that's not my default assumption. 🙃

**Comment by david-engelmann** [comment]
@h-vetinari I just saw the note and thought it applied here.

```
If you are using Conda with Python 3.9 or earlier, you must
   set ``CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1``.
```

Ill remove the conda specific parts from my PR, I'm going to try and add test for all the operating system to turbodbc so this doesn't happen often going forward

**Comment by hmaarrfk** [comment]
I'm not sure how the code is loading the library, but with ctypes, i had to use:
https://github.com/conda-forge/zaber-motion-feedstock/blob/main/recipe/patches/no_bindings_install.patch#L39

**Comment by hmaarrfk** [comment]
you can dry to use the equivalent of ldd on windows to see what it is linking to.

**Comment by david-engelmann** [comment]
[Still awaiting the resolution of this issue](https://github.com/actions/setup-python/issues/577) before adding multiple os testing to turbodbc

**Review by xhochy — CHANGES_REQUESTED** [review]
I would like to avoid merging with these patches and would simply do an upstream release instead.

**Comment by h-vetinari** [comment]
> I would like to avoid merging with these patches and would simply do an upstream release instead.

I'd say those patches look very benign, but as you wish :)

**Comment by xhochy** [comment]
Oh, yeah!

**Comment by h-vetinari** [comment]
Nice!

It's curious though that asking `turbodbc.cursor._has_arrow_support()` changes the DLL search path (resp. its result). I guess that should be fixed upstream?

**Comment by xhochy** [comment]
No, as far as I understand this is exactly how it should work.

1. On windows, there is no `RPATH`.
2. `libarrow_python.dll` is with Arrow 10+ in the site-packages folder
3. `site-packages/..` is not on the `PATH`
4. Thus, we need to inform Python where to additionally look for libs.

**Comment by xhochy** [comment]
I'm happy to change the search path somewhere else but it needs to be changed. Or do you mean that `import pyarrow` should change it already?

**Comment by h-vetinari** [comment]
> I'm happy to change the search path somewhere else but it needs to be changed. Or do you mean that `import pyarrow` should change it already?

Well, far be it for me to tell you how to design your UX, but to me `import turbodbc_arrow_support` should work out of the box, without a magical private `turbodbc.cursor._has_arrow_support()` before-hand.

From an outside perspective, turbodbc should automatically add `%SP_DIR%/pyarrow` by default for arrow >=10.

**Comment by xhochy** [comment]
> From an outside perspective, turbodbc should automatically add %SP_DIR%/pyarrow by default for arrow >=10.

I wouldn't know how to do that.

**Comment by h-vetinari** [comment]
> I wouldn't know how to do that.

Apparently the code being run in `turbodbc.cursor._has_arrow_support()` has that effect - couldn't that move to the respective `__init__.py`?

**Comment by xhochy** [comment]
> > I wouldn't know how to do that.
> 
> Apparently the code being run in `turbodbc.cursor._has_arrow_support()` has that effect - couldn't that move to the respective `__init__.py`?

`turbodbc_arrow_support` is a native module, so it doesn't have an `__init__.py`.

**Comment by h-vetinari** [comment]
> `turbodbc_arrow_support` is a native module, so it doesn't have an `__init__.py`.

Rename the native module to `_turbodbc_arrow_support` and have a thin python wrapper at `turbodbc_arrow_support/__init__.py` that jumps through all the necessary hoops?

**Comment by xhochy** [comment]
Symlinks don't reliably work on Windows AFAIK. I have not seen them working and would be surprised if that would be sustainable. 

I'm currently trying to setup a Windows CI here https://github.com/blue-yonder/turbodbc/pull/380 and once that passes, I will apply the fixes and release.

**Comment by jaimergp** [comment]
[There are a few examples in conda-forge that use `mklink`](https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Aconda-forge+mklink). It's not suuuper common, but there's a precedent hinting that it might work, maybe.

**Comment by xhochy** [comment]
Once https://github.com/blue-yonder/turbodbc/pull/382 is merged, I will make a release and then we can get this finally over the line.

**Pull request closed without merging**
